spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/quater
    username: root
    password: root
    
    
abc:
  xyz: XYZ
  mnq: MNQ
  aaa:
    bbb: BBB
    ccc: CCC
    